parameters:
    c33s_contact_form.recipients:           ~
    c33s_contact_form.sender_email:         ~
    c33s_contact_form.send_copy_to_user:    ~
#    c33s_contact_form.example.class: C33s\ContactFormBundle\Example

services:
    c33s.block.service.contact_form:
        class: C33s\ContactFormBundle\Block\ContactFormBlockService
        arguments:
            - "Contact form"
            - "@templating"
        tags:
            - { name: sonata.block }
