parameters:
    c33s_contact_form.recipients:           ~
    c33s_contact_form.sender_email:         ~
    c33s_contact_form.send_copy_to_user:    ~
#    c33s_contact_form.example.class: C33s\ContactFormBundle\Example

services:
#    c33s_contact_form:
#        arguments:  [@service_id, "plain_value", %parameter%]
